### ISSUE TITLE
Add python script for JSON generation

### ISSUE THREAD

**Issue by giselesousar** [giselesousar/treemap-js#22]
Add tutorial (README.md) for correct script usage.

**Comment by armandossrecife** [comment]
Hi Gesele, 

I have been tried to test this script locally via terminal, but I have been faced some problems. 

I performed the following steps, and the script can not be finished successfully. 

1. Setup environment variables
$ export REPOSITORY_URL=https://github.com/apache/cassandra
$ export HEATMAP_METRIC=COMPLEXITY

2. Run script json.py
$ python3 json.py

3. The script show the following output:
Cloning repository...
Cloning into 'cassandra'...
remote: Enumerating objects: 362364, done.
remote: Counting objects: 100% (192/192), done.
remote: Compressing objects: 100% (120/120), done.
remote: Total 362364 (delta 51), reused 148 (delta 34), pack-reused 362172
Receiving objects: 100% (362364/362364), 362.87 MiB | 871.00 KiB/s, done.
Resolving deltas: 100% (210556/210556), done.
Updating files: 100% (4957/4957), done.
Analyzing...
wc: cassandra: read: Is a directory
wc: cassandra/.build: read: Is a directory
wc: cassandra/ide: read: Is a directory
wc: cassandra/ide/idea: read: Is a directory
...
Traceback (most recent call last):
  File "json.py", line 212, in <module>
    run()
  File "json.py", line 205, in run
    clone_repository(url, name, heatmap_metric)
  File "json.py", line 187, in clone_repository
    analize_repository(name, heatmap_metric)
  File "json.py", line 181, in analize_repository
    create_json(root)
  File "json.py", line 54, in create_json
    outfile.write(json.dumps(json_output))
AttributeError: module 'json' has no attribute 'dumps'

**Comment by giselesousar** [comment]
Apparently the error was related to the script filename. All corrections have been made.

**Comment by armandossrecife** [comment]
The file name json.py was changed to create_json.py
